---
title: "BST 260 Group Project"
author: "Christina, Dena, Jack, Veronica, Whitney"
date: "11/22/2021"
output: html_document
---

```{r}
#some basic packages that we will probably want: 
library(tidyverse)
library(lubridate)
library(rvest)

#package to read in xlsx files from a url:
library(openxlsx)
```

Analysis 1: Data scraping, cleaning and merging

Obtain County Health Ranking Data sheets, as well as county-level COVID data from NYT:

```{r}
#County Health Ranking Data:
dat <- read.xlsx("https://www.countyhealthrankings.org/sites/default/files/media/document/2021%20County%20Health%20Rankings%20Data%20-%20v1.xlsx", sheet = 4, startRow = 2)

#County Health Ranking Data second sheet:
dat2 <- read.xlsx("https://www.countyhealthrankings.org/sites/default/files/media/document/2021%20County%20Health%20Rankings%20Data%20-%20v1.xlsx", sheet = 6, startRow = 2)

#Cumulative County-level COVID data:
covid_dat <- read.csv(url("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv"))
```

Web scraping for County names and population from Wikipedia:

```{r}

url <- "https://en.wikipedia.org/wiki/List_of_United_States_counties_and_county_equivalents"
tab = read_html(url) %>% html_nodes("table")

county_names <- c("county", "state", "population_2019", "delete")
counties <- tab %>% .[1] %>% html_table %>% .[[1]] %>% setNames(county_names)

counties <- counties %>% 
  select(!delete)

#make population_2019 numeric:
counties$population_2019 <- as.numeric(gsub(",","", counties$population_2019))

```

Data Manipulation and Merging:

```{r}
#Filter COVID data to most recent date, then arrange by state:
covid_dat <- covid_dat %>%
  filter(date == '2021-11-21') %>%
  select(!fips) %>%
  arrange(state)

#Make a list of the column names that we're interested in for dat:
columns <- c("FIPS",	"State",	"County", "Years.of.Potential.Life.Lost.Rate", "%.Fair.or.Poor.Health", "Average.Number.of.Physically.Unhealthy.Days",	"Average.Number.of.Mentally.Unhealthy.Days",	"%.Low.birthweight",	"%.Smokers", "%.Adults.with.Obesity",	"Food.Environment.Index",	"%.Physically.Inactive",	"%.With.Access.to.Exercise.Opportunities",	"%.Excessive.Drinking",	"#.Alcohol-Impaired.Driving.Deaths",	"#.Driving.Deaths",	"%.Driving.Deaths.with.Alcohol.Involvement",	"Chlamydia.Rate",	"Teen.Birth.Rate",	"%.Uninsured", "Primary.Care.Physicians.Rate",	"Primary.Care.Physicians.Ratio",	"Dentist.Rate",	"Dentist.Ratio",	"Mental.Health.Provider.Rate",	"Mental.Health.Provider.Ratio",	"Preventable.Hospitalization.Rate",	"%.With.Annual.Mammogram",	"%.Vaccinated",	"%.Completed.High.School",	"%.Some.College",	"%.Unemployed",	"%.Children.in.Poverty",	"Income.Ratio",	"%.Children.in.Single-Parent.Households",	"Social.Association.Rate", "Violent.Crime.Rate",	"Injury.Death.Rate",	"Average.Daily.PM2.5",	"Presence.of.Water.Violation", "%.Severe.Housing.Problems",	"%.Drive.Alone.to.Work", "%.Long.Commute.-.Drives.Alone")

#Keep only the columns from our list above, rename to match COVID data, arrange by state:
dat <- dat %>%
  select(columns) %>%
  rename(county = County) %>%
  rename(state = State) %>%
  rename(fips = FIPS) %>%
  arrange(state)

#Make a list of the column names we're interested in for dat2:
columns2 <- c("FIPS",	"State",	"County", "Life.Expectancy",	"Age-Adjusted.Death.Rate",	"Child.Mortality.Rate",	"Infant.Mortality.Rate",	"%.Frequent.Physical.Distress",	"%.Frequent.Mental.Distress",	"%.Adults.with.Diabetes",	"HIV.Prevalence.Rate",	"%.Food.Insecure",	"%.Limited.Access.to.Healthy.Foods",	"Drug.Overdose.Mortality.Rate",	"Motor.Vehicle.Mortality.Rate",	"%.Insufficient.Sleep",	"%.Disconnected.Youth",	"Average.Grade.Performance",	"Median.Household.Income",	"%.Enrolled.in.Free.or.Reduced.Lunch",	"Homicide.Rate",	"Suicide.Rate.(Age-Adjusted)",	"Firearm.Fatalities.Rate",	"Juvenile.Arrest.Rate",	"%.Homeowners",	"%.Broadband.Access",	"%.Female",	"%.Rural")

#Keep only the columns from our list above, rename to match COVID data, arrange by state:
dat2 <- dat2 %>%
  select(columns2) %>%
  rename(county = County) %>%
  rename(state = State) %>%
  rename(fips = FIPS) %>%
  arrange(state)

#Merge dat with dat2, then merge with COVID data:
dat <- dat %>%
  inner_join(dat2, by=c("fips", "county", "state"))

dat <- dat %>%
  inner_join(covid_dat, by=c("county", "state"))

#Finally, merge dat with counties for population:
dat <- dat %>%
  inner_join(counties, by=c("county", "state"))

```

Analysis 2:

```{r}
##box plot of household income per state 
p <- dat %>% 
  mutate(state = reorder(state, Median.Household.Income, FUN = median, is.na(Median.Household.Income))) %>%
  ggplot(aes(state, Median.Household.Income, fill = state)) +
  geom_boxplot() + 
  theme_bw() +
  ggtitle("Boxplots of Median Household Income by State")  +
  theme_update(plot.title = element_text(hjust = 0.6)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  xlab("State") + ylab("Median Household Income")+
  theme(legend.position = "none")
p 


```

Analysis 3:

```{r}
#box plot of life expectancy by state
p2 <- dat %>% 
  mutate(state = reorder(state, Life.Expectancy, FUN = median), is.na(Life.Expectancy)) %>%
  ggplot(aes(x = reorder(state, Life.Expectancy), y = Life.Expectancy, fill = state)) +
  geom_boxplot() + 
  theme_bw() +
  theme(legend.position = "none") + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  theme(plot.title = element_text(hjust = 0.5)) + 
  ggtitle("Boxplots of Life Expectancy by State") + 
  xlab("State") + ylab("Life Expectancy (years)")

p2


###Extra code
#something <- dat %>% select(state, Life.Expectancy, county) %>% group_by(state) %>%
#                 mutate(median_life = median(Life.Expectancy)) %>% ungroup()
#something

#something2 <- dat %>% filter(state == "Mississippi", !is.na(Life.Expectancy))
#something2
#median(something2$Life.Expectancy)



```

Analysis 4:

```{r}
#dat %>% select(county, state, Life.Expectancy) %>% arrange(Life.Expectancy)

p3 <- dat %>% select(county, state, Life.Expectancy) %>% arrange(Life.Expectancy)%>% 
          filter(Life.Expectancy <= 70.14277)

#creating a line plot of descending order of life expectancy
p4 <- p3 %>% ggplot(aes(x = reorder(county, -Life.Expectancy), y = Life.Expectancy, group = 1)) +
            geom_point() +
            geom_line() + 
            theme_bw() + 
            ggtitle("Top 25 Counties With the Shortest Life Expectancy in the United States") +
            theme(plot.title = element_text(hjust = 0.5)) + 
            theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
            xlab("U.S County") + ylab("Life Expectancy (years)") 

p4 + scale_x_discrete("U.S. County", labels = c("Oglala Lakota" = "Oglala Lakota (SD)", "Buffalo" = " Buffalo (SD)", "Corson" = "Corson (SD)", "Mellette" = " Mellette (SD)","Todd" = " Todd (SD)", "Roosevelt" = "Roosevelt (MT)", "Dewey" = "Dewey (SD)", 
                                             "Big Horn" = "Big Horn (MT)", "Union" = "Union (FL)", "Sioux" = "Sioux (ND)", "Perry" = "Perry (KY)",  "Kingman" = "Kingman (KS)", "McDowell" = "McDowell (WV)", "Edwards" = "Edwards (KS)", "Bennett" = "Bennett (SD)", "Owsley" = "Owsley (KY)", "Thurston" = "Thurston (NE)", "Breathitt" = "Breathitt (KY)", "Okfuskee" = "Okfuskee (OK)", "Logan" = "Logan (WV)", "Monroe" = "Monroe (AL)", "Powell" = "Powell (KY)", "Tunica" = "Tunica (MS)", "Sharkey" = "Sharkey	(MS)", "Mahnomen" = "Mahnomen (MN)"))



```

Analysis 5:

```{r}

#head(dat$Life.Expectancy)
#class(dat$Life.Expectancy)
#mean(dat$Life.Expectancy, na.rm = TRUE)
##histogram of life expectancy in the united states
p5 <- dat %>% ggplot(aes(x = Life.Expectancy)) +
              geom_histogram(binwidth = 0.2, color = "black", fill = "light blue") + 
              theme_bw()+ 
              ggtitle("Life Expectancy Distribution in the United States") +
              theme(plot.title = element_text(hjust = 0.5)) +
              xlab("Life Expectancy") 

p5 + geom_vline(aes(xintercept = mean(Life.Expectancy, na.rm = TRUE)), col='dark red',size=1)


```

Analysis 6:

```{r}
#####Drug Overdose Mortality
p6 <- dat %>% ggplot(aes(x = `Drug.Overdose.Mortality.Rate`)) +
              geom_histogram(binwidth = 0.75, color = "black", fill = "gray") + 
              theme_bw()+ 
              ggtitle("Distribution of Drug Overdose Mortality Rates per 100,000 population in the U.S.") +
              theme(plot.title = element_text(hjust = 0.5)) +
              xlab("Drug Overdose Mortality Rate (per 100,000 population)") 
p6 + geom_vline(aes(xintercept = median(`Drug.Overdose.Mortality.Rate`, na.rm = TRUE)), col='dark red',size=1) 

#median(dat$`Drug.Overdose.Mortality.Rate`, na.rm = TRUE)

```

```{r}
p7 <- dat %>% 
  ggplot(aes(x = reorder(state, Drug.Overdose.Mortality.Rate) , y = Drug.Overdose.Mortality.Rate, fill = state))+
  geom_boxplot() + 
  theme_bw() +
  ggtitle("Boxplots of Drug Overdose Mortality Rate by State")  +
  theme_update(plot.title = element_text(hjust = 0.5)) + 
  theme(axis.text.x = element_text(angle = 90, hjust = 0.5)) +
  theme(axis.text.y = element_text(size = 0.1)) + ##need to adjust the size of text 
  xlab("State") + ylab("Drug Overdose Mortality Rate per 100,000 Population")+ #change size of text
  theme(legend.position = "none")

p7 

#something2 <- dat %>% filter(state == "Ohio", !is.na(Drug.Overdose.Mortality.Rate))
#something2
#median(something2$Drug.Overdose.Mortality.Rate)

```

```{r}
p8 <- dat %>% select(county, state, Drug.Overdose.Mortality.Rate) %>% arrange(Drug.Overdose.Mortality.Rate) %>%
          filter(Drug.Overdose.Mortality.Rate >= 61) 
#p8

#creating a line plot of descending order of life expectancy
p9 <- p8 %>% ggplot(aes(x = reorder(county, Drug.Overdose.Mortality.Rate), y = Drug.Overdose.Mortality.Rate, group = 1)) +
            geom_point() +
            geom_line() + 
            theme_bw() + 
            ggtitle("Top 25 Counties With the Highest Drug Overdose Mortality Ratio in the United States") +
            theme(plot.title = element_text(hjust = 0.5)) + 
            theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
            xlab("U.S County") + ylab("Drug Overdose Mortality Ratio (per 100,000 population)") 

p9 + scale_x_discrete("U.S. County", labels = c("Kenton" = "Kenton (KY)", "Lake" = " Lake (CA)", "Cheatham" = "Cheatham (TN)", "Hampshire" = " Hampshire (WV)", "Owen" = "Owen (KY)", "Gallia" = "Gallia (OH)", "Lincoln" = "Lincoln (WV)", "Boyd" = "Boyd (KY)", "Union" = "Union (IN)", "Estill" = "Estill (KY)", "Fayette" = "Fayette (WV) & (IN)", "Mahnomen" = "Mahnomen (MN)", "Cecil" = "Cecil (MD)", "Montgomery" = "Montgomery (OH)", "Kanawha" = "Kanawha (WV)", "Gallatin" = "Gallatin (KY)", "Boone" = "Boone (WV)", "Rio Arriba" = "Rio Arriba (NM)", "Raleigh" = "Raleigh (WV)", "Wayne" = "Wayne	(IN)", "Scioto" = "Scioto (OH)", "Logan" = "Logan (WV)", "Wayne" = "Wayne (WV)", "Cabell" = "Cabell (WV)", "Berkeley" = "Berkeley (WV)"))


```

```{r}
###Scatter plot of drug over dose mortality and life expectancy 
p10 <- dat %>% ggplot(aes(x = Drug.Overdose.Mortality.Rate, y = Life.Expectancy)) +
            geom_point(size = 1) + 
            ggtitle("Scatter Plot of Life Expectancy vs. Drug Overdose Mortality Rate (per 100,000 population)") +
            theme(plot.title = element_text(size = 10)) + 
            xlab("Drug Overdose Mortality Rate (per 100,000 population)") + 
            ylab("Life Expectancy (years)") 
    
p10 + geom_smooth(method = "lm")

```

```{r}
####Food Insecurity

p11 <- dat %>% select(county, state, `%.Food.Insecure`) %>% arrange(`%.Food.Insecure`)%>% 
          filter(`%.Food.Insecure` >= 23.9)
#p11

#creating a line plot of descending order of life expectancy
p12 <- p11 %>% ggplot(aes(x = reorder(county, `%.Food.Insecure`), y = `%.Food.Insecure`, group = 1)) +
            geom_point() +
            geom_line() + 
            theme_bw() + 
            ggtitle("Top 25 Counties With the Highest Food Insecurity % in the United States") +
            theme(plot.title = element_text(hjust = 0.5)) + 
            theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
            xlab("U.S County") + ylab("Food Insecurity %") 

p12 + scale_x_discrete("U.S. County", labels = c("Chicot" = "Chicot (AR)", "Coahoma" = "Coahoma (MS)", "Bolivar" = "Bolivar (MS)", "Clay" = " Clay (GA) & Clay (KY)", "Leflore" = "Leflore (MS)", "Wolfe" = "Wolfe (KY)", "Washington" = "Washington (MS)", "Breathitt" = "Breathitt (KY)", "Wilcox" = "Wilcox (AL)", "Bell" = "Bell (KY)", "Magoffin" = "Magoffin (KY)", "Harlan" = "Harlan (KY)", "Wilkinson" = "Wilkinson (MS)", "Quitman" = "Quitman (MS)", "Phillips" = "Phillips (AR)", "Todd" = "Todd (SD)", "Greene" = "Greene (AL)", "Humphreys" = "Humphreys (MS)", "Oglala Lakota" = "Oglala Lakota (SD)", "Perry" = "Perry (AL)", "Claiborne" = "Claiborne (MS)", "Holmes" = "Holmes (MS)", "Issaquena" = "Issaquena (MS)", "Jefferson" = "Jefferson (MS)"))




```
```{r}
####%Housing Problems 
p13 <- dat %>% select(county, state, `%.Severe.Housing.Problems`) %>% arrange(`%.Severe.Housing.Problems`)%>% 
          filter(`%.Severe.Housing.Problems` >= 26.43805)

#p13

#creating a line plot of descending order of life expectancy
p14 <- p13 %>% ggplot(aes(x = reorder(county, `%.Severe.Housing.Problems`), y = `%.Severe.Housing.Problems`, group = 1)) +
            geom_point() +
            geom_line() + 
            theme_bw() + 
            ggtitle("Top 25 Counties With the Highest Severe Housing Problems % in the United States") +
            theme(plot.title = element_text(hjust = 0.5)) + 
            theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
            xlab("U.S County") + ylab("Food Insecurity %") 

p14 + scale_x_discrete("U.S. County", labels = c("Imperial" = "Imperial (CA)", "Mendocino" = "Mendocino (CA)", "Tunica" = "Tunica (MS)", "Rockland" = " Rockland (NY)", "Orange" = "California (CA)", "Ziebach" = "Ziebach (SD)", "Fresno" = "Fresno (CA)", "Tulare" = "Tulare (CA)", "Santa Cruz" = "Santa Cruz (CA)", "Todd" = "Todd (SD)", "Essex" = "Essex (NJ)", "Alpine" = "Alpine (CA)", "Hudson" = "Hudson (NJ)", "San Miguel" = "San Miguel (CO)", "McKinley" = "McKinley (NM)", "Webb" = "Webb (TX)", "Santa Barbara" = "Santa Barbara (CA)", "Buffalo" = "Buffalo (SD)", "Monterey" = "Monterey (CA)", "Miami-Dade" = "Miami-Dade (FL)", "Passaic" = "Passaic (NJ)", "Apache" = "Apache (AZ)", "Madison" = "Madison (ID)", "Los Angeles" = "Los Angeles (CA)", "Oglala Lakota" = "Oglala Lakota	(SD)"))



```


```{r, warning=FALSE}
# Map of life expectancy by drug overdose deaths
library(biscale)
library(rgdal)
library(ggplot2)
library(sf)
library(sp)
library(tibble)
library(cowplot)
library(ggsn)
library(rgeos)
library(raster)
library(staplr)

county_shp <- rgdal::readOGR(".", layer = "cb_2018_us_county_20m",
                            verbose = F)

county_sf <- as(county_shp, "sf")

county_sf <- county_sf %>% mutate(fips = paste(STATEFP, COUNTYFP, sep = ""))

dat_subset <- select(dat2, c(FIPS, Drug.Overdose.Mortality.Rate, Life.Expectancy))

county_sf <- left_join(county_sf, dat_subset, by = c("fips" = "FIPS"))

county_sf <- county_sf %>% filter(STATEFP != "14" & STATEFP != "03" & STATEFP != "43" & STATEFP != "52" & STATEFP != "78" & STATEFP != "79" & STATEFP != "74" & STATEFP != "72" & STATEFP != "69" & STATEFP != "70" & STATEFP != "95" & STATEFP != "71" & STATEFP != "76" & STATEFP != "68" & STATEFP != "89" & STATEFP != "67" & STATEFP != "86" & STATEFP != "84" & STATEFP != "66" & STATEFP != "64" & STATEFP != "81" & STATEFP != "60" & COUNTYFP != "016")

county_sf_no_od_na <- county_sf %>% filter(is.na(Drug.Overdose.Mortality.Rate) == FALSE)
```


```{r}
od_le_class <- bi_class(county_sf_no_od_na, x = Drug.Overdose.Mortality.Rate, y = Life.Expectancy, style = "quantile", dim = 3)

map_county <- ggplot() + 
  geom_sf(data = filter(county_sf, STATEFP != "15" & STATEFP != "02"), fill = NA, color = "black", size = 0.3, show.legend = FALSE) + 
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.title = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))

map_county_hi <- ggplot() + 
  geom_sf(data = filter(county_sf, STATEFP == "15"), fill = NA, color = "black", size = 0.3, show.legend = FALSE) + 
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.title = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))

map_county_ak <- ggplot() + 
  geom_sf(data = filter(county_sf, STATEFP == "02"), fill = NA, color = "black", size = 0.3, show.legend = FALSE) + 
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.title = element_blank(),
        panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = "transparent",colour = NA),
        plot.background = element_rect(fill = "transparent",colour = NA))

map_od_le <- ggplot() +
  geom_sf(data = filter(od_le_class, STATEFP != "15" & STATEFP != "02"), mapping = aes(fill = bi_class),
          color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue", dim = 3) +
  bi_theme() +
  north(od_le_class, scale = 0.12) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.title = element_blank(),
        rect = element_blank())

map_od_le_hi <- ggplot() +
  geom_sf(data = filter(od_le_class, STATEFP == "15"), mapping = aes(fill = bi_class),
          color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue", dim = 3) +
  bi_theme() +
  north(od_le_class, scale = 0.12) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.title = element_blank(),
        rect = element_blank())

map_od_le_ak <- ggplot() +
  geom_sf(data = filter(od_le_class, STATEFP == "02"), mapping = aes(fill = bi_class),
          color = "white", size = 0.1, show.legend = FALSE) +
  bi_scale_fill(pal = "DkBlue", dim = 3) +
  bi_theme() +
  north(od_le_class, scale = 0.12) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.title = element_blank(),
        rect = element_blank())

legend_od_le <- bi_legend(pal = "DkBlue",
                    dim = 3,
                    xlab = "Higher OD Rate",
                    ylab = "Higher LE",
                    size = 8)

od_le_bivariate <- ggdraw() +
  draw_plot(map_od_le, 0, 0, 1, 1) +
  draw_plot(legend_od_le, 0.7, 0.01, 0.25, 0.25) +
  draw_plot(map_od_le_hi, 0.2, 0.01, 0.2, 0.2) + 
  draw_plot(map_od_le_ak, 0.05, 0.08, 0.211, 0.211) + 
  draw_plot(map_county, 0.022, 0.02, 0.96, 0.96) + 
  draw_plot(map_county_hi, 0.223, 0.024, 0.16, 0.16) +
  draw_plot(map_county_ak, -0.05, 0.018, 0.35, 0.35)

od_le_bivariate
```

